### ISSUE TITLE
Improve the description of the date macro

### ISSUE THREAD

**Issue by michitux** [xwikisas/application-task#103]
The description of the date macro is currently "Customize the way you want to display a date." which isn't really fitting in my opinion. Sure, it has options for that, but the main purpose of the date macro is entering a due date inside a task macro from my understanding and I think this should be mentioned in the macro's description. That way, it would also be easier to find in the quick actions, e.g., by typing `/due`.

**Comment by Farcasut** [comment]
@michitux Do you think that this description is more fitting?
Use the date macro to set and format due dates within task macros and more! Additionally, you can use the /due command for quick actions.

**Comment by michitux** [comment]
I'm not suggesting to document a `/due` command that doesn't exist. My point was more that if "due date" is mentioned in the description, the macro will be listed when you type `/due` and is thus much more discoverable. I think "Use the date macro to set and format due dates within task macros and more!" is okay, but I would check the description of other macros as comparison. I think at least within the pro macros, descriptions should have a consistent style (by style I mean the use of exclamation marks, active/passive voice, …).
