### ISSUE TITLE
This application makes use of the internal AbstractMacroConverter API of confluence-xml

### ISSUE THREAD

**Issue by raphj** [xwikisas/application-task#106]
This is an issue because as per the XWiki community rules, compatibility can be broken at any time.

See https://jira.xwiki.org/browse/CONFLUENCE-240 about making this API public, which would solve the issue but the paths packages will need to be updated in this application's code.

**Comment by trrenty** [comment]
As of #109, the application does not make use of `AbstractMacroConverter` anymore.
