### ISSUE TITLE
The task report macro should show tasks in all sub spaces recursively

### ISSUE THREAD

**Issue by raphj** [xwikisas/application-task#111]
In "Space A", I have "My Home Page", and as children Page A and Page B. Page A and Page B.

if I add the task report macro to Space A.WebHome, I expect it to show the tasks in Page A and Page B, or to have the option to make it show those tasks.

This is the expectation for people migrating from confluence, so the bridge and the converter should reflect this as well.

**Comment by Farcasut** [comment]
@raphj 
I need some clarification. Do you want the ability to automatically see all the tasks in the current space where the macro was called? The macro already shows tasks recursively when you select a page, and it also the default option to search everywhere.

Macro call:
![image](https://github.com/user-attachments/assets/64f0c6a2-4dd5-4314-8386-4a70e95e333d)
Space structure:
![image](https://github.com/user-attachments/assets/4f319296-d9f6-47da-b219-77bcd70510c8)
Result:
![image](https://github.com/user-attachments/assets/ade69ea4-d164-41b2-8cba-e6e83fdb82c0)
