### ISSUE TITLE
The checkbox of a task containing subtasks is misaligned

### ISSUE THREAD

**Issue by raphj** [xwikisas/application-task#134]
The following XWiki syntax:

```
{{task reference="/Tasks/Task_39" status="InProgress"}}
A big task containing several subtask:

(% class="task-list" %)
(((
 

{{task reference="/Tasks/Task_40" status="InProgress"}}
a first subtask
{{/task}}

{{task reference="/Tasks/Task_41" status="InProgress"}}
a second subtask
{{/task}}

{{task reference="/Tasks/Task_42" status="InProgress"}}
a third subtask
{{/task}}
)))
{{/task}}
```

is rendered as:

![image](https://github.com/user-attachments/assets/070cc51d-3a5c-4855-8d8c-35521b6dcac8)

expected:

![image](https://github.com/user-attachments/assets/e98466cd-7f85-46c4-b1d6-0e78f371190d)

That is:
 - important: the checkbox should be aligned with the first line
 - nice to have: the first subtask should be closer to the first task
 - idea: think about the left margin of the subtask, but it's probably already good as is
 -

**Comment by trrenty** [comment]
Note that right now the application is affected by this issue: https://github.com/xwikisas/application-task/issues/81

It will cause you to lose the subtasks if you click on the checkbox of the main task. (can still be recoverable through history)

**Comment by KebabRonin** [comment]
For your second point, the extra space is due to the two newlines in the `task-list` div, removing one of them fixed the spacing between the subtask and the main task.
