### ISSUE TITLE
Date macro is not rendered correctly when setting a specific format in localization

### ISSUE THREAD

**Issue by lamblinc** [xwikisas/application-task#144]
Steps to reproduce:

- In the admin panel, Localization settings, set a specific date format (for example YYYY-MM-dd HH:mm)
- Add a date macro in a page

Expected result: the date is displayed correctly

Actual result: the date displayed is a day in December of the specified year, even if the parameter of the macro is in another month.

For example, macro parameter:
{{date value="2064-06-20 16:51"/}}

Rendering:
![image](https://github.com/user-attachments/assets/edc11ea3-8891-44de-8706-9f54cfb8e997)

Side note: when modifying the localization setting after adding a date macro, the page that includes a macro displays an error message (Failed to execute the [date] macro. Cause: [Failed to parse the given date, expected format [YYYY-MM-dd HH:mm]!]. Click on this message for details.), you have to edit the macro and save to get the display back)

**Comment by trrenty** [comment]
In the example you presented, the storage format `YYYY-MM-dd HH:mm` is not correct. If i changed it to `yyyy-MM-dd HH:mm` (lowercase y), it would display the expected date.
![image](https://github.com/user-attachments/assets/9e7540ce-e770-4f76-9650-1c0109cf75f2)

About the error message you get after changing the storage format, it is expected. The storage format is used mostly in the case of the picker - so it knows what format to use to autofill the value parameter. Once the storage format is changed, the macros that were already with the old storage format will not be valid anymore.

Ideally, we would have a job that searches all the pages that contain the date macro and update the  value parameter according to the new storage format. However, handling such a big number of pages can always have unforeseen consequences.

Let me know if this fixes your issue.
