### ISSUE TITLE
Cannot add a list of tasks in a page in a bulleted or ordered list

### ISSUE THREAD

**Issue by lucaa** [xwikisas/application-task#25]
How to reproduce:
* create a page
* create a paragraph 
* create a list of tasks after it
* in the first list item, add a new task

Expected result: be able to create a todo list of tasks as a list in the editor

Actual result: the task macro cannot be used inline:
![image](https://github.com/xwikisas/application-task/assets/657716/41306c3d-5eb7-4a38-9ec9-4f48c7c6b848)

**Comment by mflorea** [comment]
This looks like an XWiki rendering bug to me. List items support block content both in HTML and wiki syntax. That's not an in-line context. Note that you can reproduce this with any block macro (that doesn't support in-line mode).

> Actual result: the task macro cannot be used inline

It's not supposed to be used inline, i.e. inside a paragraph, between text. But in this case the list item is wrongly considered an in-line context. I suggest you report an issue on the rendering side.
