### ISSUE TITLE
Adding a task at the end of a list of tasks focuses the previously added tasks, when adding tasks from the editor in a page

### ISSUE THREAD

**Issue by lucaa** [xwikisas/application-task#26]
How to reproduce (reproduced on Chrome and on XWiki 14.10.7:
* create a page
* create a "list of tasks" in this page, as follows:
  * on subsequent lines, add task macros one after the other to make a list of tasks
* when adding a new task at the end of the list the steps are the following:
  * position the caret in the editor on a next line following the last task from the list
  ![image](https://github.com/xwikisas/application-task/assets/657716/e5cd8138-200c-4c5b-abdc-0dd625b43d0c)
  * go to the + menu on the editor bar, choose other macros, choose Task Macro, fill in the parameters and hit "Submit":
  ![image](https://github.com/xwikisas/application-task/assets/657716/dde30cf4-cf5d-44bb-a34f-9cbb88976ecd)
  * the new task is inserted in the page, on the line where the caret was

Actual result:
* The _previous_ task from the list is now selected, right after insertion:
![image](https://github.com/xwikisas/application-task/assets/657716/c8608dcc-1b8d-456b-a1ad-7a16d709b371)
* Also, it's rather hard to move the focus elsewhere: I am trying to click on the paragraph after the list of tasks, or a paragraph I had before the list of tasks, or a title, nothing works.

Expected result:
* Either the currently added task should be selected (as when adding a single task in a page) or no task should be selected.

**Comment by mflorea** [comment]
> Also, it's rather hard to move the focus elsewhere: I am trying to click on the paragraph after the list of tasks, or a paragraph I had before the list of tasks, or a title, nothing works.

I can't reproduce this, neither with the in-place editor nor with the standalone editor. Clicking outside the macro moves the caret as expected for me.

As for the selected task macro, I think this is a CKEditor Integration issue. The task macro can't do anything about this (besides generating valid HTML, which already does).

**Comment by mflorea** [comment]
> As for the selected task macro, I think this is a CKEditor Integration issue.

I can reproduce by inserting consecutive box macros (info, warning, error). I suggest you report an issue on platform.
