### ISSUE TITLE
Missing spaces and wrong font on the template fields

### ISSUE THREAD

**Issue by petrenkonikita112263** [xwikisas/application-task#36]
Tested on 14.10.6 XWiki.

**STEPS TO REPRODUCE**

1. Install latest version of the application v3.0.2
2. Get trial license
3. Go to home page of Task Manager
4. Press "Create" and name new task "Task A"
5. Select Task Template
6. Press "Next"

**ACTUAL RESULT**
Some name of the fields miss space, also it looks like field "A Task", the letter A uses a different font. Or even the wrong name it should be "Task name". 
![image](https://github.com/xwikisas/application-task/assets/56109799/a288de5d-5359-4c1e-9b35-bde67a7ed74b)

**EXPECTED RESULT**
Field names have spaces as it exist for the "Due date" field, and the first field name has same font as others.

**Comment by petrenkonikita112263** [comment]
I see that letter "A" is not a letter, but a simple icon, but it's a bit interflow with the word "Task". Better to change icon representation that won't have the same visual interflow as the default XWiki setting.

**Comment by snazare** [comment]
replace the icon next to the task name. 
fix the translations for the create date and complete date.
