### ISSUE TITLE
Task report macro wrongly filter tasks

### ISSUE THREAD

**Issue by petrenkonikita112263** [xwikisas/application-task#38]
XWiki 14.10.6, with lates version of extension v3.0.2

**STEPS TO REPRODUCE**

![image](https://github.com/xwikisas/application-task/assets/56109799/f6119991-1545-491f-89c4-cacfdaf04977)

1. Create several tasks with different status "To Do", "In Progress" and "Done"
2. Go to any dedicated page or sandbox, and add task report macro or easily copy/paste this code in source of the page

`{{task-report pages="TaskManager.WebHome" columns="name,assignee,status,duedate,completeDate,owner" status="ToDo"/}}`

![image](https://github.com/xwikisas/application-task/assets/56109799/bd169ae6-29b5-450d-bde0-f4d4d4275fce)

**ACTUAL RESULT**
Macro prints wrongly tasks, in livetable you'll see tasks with status "In Progress"
![image](https://github.com/xwikisas/application-task/assets/56109799/101951c9-e262-4990-baca-46b943b5b7cf)

**EXPECTED RESULT**
Macro displays tasks with status "ToDo"

**Comment by snazare** [comment]
i reproduce on 14.10.13 weather I insert the macro in wiki mode or wysiwyg.
