### ISSUE TITLE
Task title for non-terminal page isn't displayed

### ISSUE THREAD

**Issue by petrenkonikita112263** [xwikisas/application-task#39]
XWiki 14.10.6, application v3.0.2, MS Edge latest version

**STEP TO REPRODUCE**

1. Install latest version of app 3.0.2
2. Obtain trial license
3. Navigate into home page of Task Manager
4. Press "Create"
5. Name the task "Task Now"
6. Uncheck terminal page
7. Press "Next"
8. Finally press "Save"

**ACTUAL RESULT**
The name of the task isn't present instead of display velocity code. However in the URL the name "Task%20Now" is present.

![image](https://github.com/xwikisas/application-task/assets/56109799/50d8e819-54b8-4b64-8173-6ee5fd447fb4)
![image](https://github.com/xwikisas/application-task/assets/56109799/81b4228e-2f4b-4b67-9976-73510f6a8c94)
![image](https://github.com/xwikisas/application-task/assets/56109799/45911fdf-3598-441d-b2c3-b286b992d245)

**EXPECTED RESULT**
The name "Task Now" is visible in table, and in web browser tab

**Comment by snazare** [comment]
I reproduce on 14.10.13, but I am not sure if this is a bug or not. @trrenty should task pages should be able to have children?
