### ISSUE TITLE
Wrongly named extension pages

### ISSUE THREAD

**Issue by petrenkonikita112263** [xwikisas/application-task#41]
![image](https://github.com/xwikisas/application-task/assets/56109799/c2dc402c-413b-4884-925b-9f617ac8f84a)

The point of this page is to add a new priority to existing ones (Low, Medium, High). The page has the "Add priority" button with the list of priorities. However, the page is named "AdministrationAddSeverity". If to check previous pages that are similar "AdministrationAddProject".

Preferable to name "AdministrationAddPriority" or rename the mentioned pages to "AddPriority" the same as "Add Status". 

![image](https://github.com/xwikisas/application-task/assets/56109799/a1953889-4174-4677-b70e-1731f75f921b)

![image](https://github.com/xwikisas/application-task/assets/56109799/11ecfa4b-cb82-4744-8fda-9dd11a46125f)

![image](https://github.com/xwikisas/application-task/assets/56109799/ab440348-fa47-491e-b1e3-c9aabe44815f)

**Comment by snazare** [comment]
These are code pages that are hidden and should not be accessed by users. 

Moreover, the administration should be done through the task manager administration section.
