### ISSUE TITLE
Reduce number of extension pages

### ISSUE THREAD

**Issue by petrenkonikita112263** [xwikisas/application-task#43]
Currently, if the user wants to add custom status, priority, and project. It can be done as singular action - navigating to each dedicated page. However, the same can be done from one page "TaskManager.Administration" directly, depending on what the user wants (new status, priority, or project)

Why not to remove this pages (which are present) - "TaskManager.AdministrationAddSeverity", "TaskManager.AdministrationAddStatus", "TaskManager.AdministrationAddProject" and leave only "TaskManager.Administration".

![image](https://github.com/xwikisas/application-task/assets/56109799/2c3eb592-f85a-4e30-8051-fff762efc45a)

**Comment by snazare** [comment]
These are code pages that are hidden and should not be accessed by users.
