### ISSUE TITLE
Create automated tests

### ISSUE THREAD

**Issue by snazare** [xwikisas/application-task#46]

**Comment by trrenty** [comment]
Created various integration tests that will assure:
* Simple task macros are displayed properly
* The checkbox of a task macro functions as expected
* The content of the task macro is rendered properly (mention and date macros work)
* The created task page corresponds with the data present in the macro
* The livetable from the application homepage displays the created tasks
* Modifying the task macro will also modify the task page
* Modifying the task page will also modify the task macro
* Deleting a page that has in its content task macros will delete the pages associated with the macros
* Deleting a task page will remove the the macro call from the owner page
* The task report macro displays well
* The task report macro status filter functions properly

More integration tests should be added to cover other things such as:
* All other filters of the task report macro (filtering by page tags, location, assignee, reporter, creation date, etc)
* All the other macros (tasks, task-card, kanban board, date)
* Adding new priorities, statuses, severities in the administration section
