### ISSUE TITLE
Dynamic change of progress bar in Kanban board during drag/drop tasks from ToDo into Done and vise-versa

### ISSUE THREAD

**Issue by petrenkonikita112263** [xwikisas/application-task#51]
Currently, after having several tasks with different statuses and after the call `{{kanbanboard project="Testing"/}}`, assuming that all tasks were created in TaskManager space and by Admin user as default values. The user can easily drag & drop tasks from ToDo or any other column in desired place. As a result status of tasks is changed in the background (pop-up message "The XWiki data has been updated"). If to check the livetable in the "TaskManager.WebHome" page after refreshing the table - the task status that was dragged and dropped, it changed to the appropriate value.

What also can be a good feature is that not only the statusб but the progress automatically changes when dragging from ToDo place to Done - and received a value of 100. And vice versa from Done to ToDo with a value of 0.

**Comment by petrenkonikita112263** [comment]
From what I've checked and it's [documented](https://store.xwiki.com/xwiki/bin/view/Extension/TaskApplication#HInsidethecontentofapage). Currently, this feature is only available for Task macro or Task list macro. 

>you can click on the checkbox beside each task to mark it as 'Done' or 'In Progress'.

What's not documented, that Progress is also changing during this, if for instance the task was done for 5% by checking it, it'll be transformed into Done with progress 100%. Performing vise-versa it resets progress to 0 and status In Progress. 

Then this feature can be present for Task Kanban macro with changed title of this feature or improvement from InProgress into Done.

**Comment by snazare** [comment]
related to #15

**Comment by petrenkonikita112263** [comment]
Sorry @snazare , missed your comment. I'm closing this as a duplicate ticket.

**Comment by petrenkonikita112263** [comment]
I checked the new version, and the synchronization works inside the task itself, but not on Kanboard. Only the status is changed.

**Comment by oanalavinia** [comment]
> I checked the new version, and the synchronization works inside the task itself, but not on Kanboard. Only the status is changed. Reported as a new bug and closing this.

Hi, @petrenkonikita112263 ! Can you point to the new bug you created?
Also, I added the `Won't fix` label. Feel free to change it if needed (maybe `Duplicate` or `Invalid`?)
