### ISSUE TITLE
The avatar doesn't have a link to assignee user profile

### ISSUE THREAD

**Issue by petrenkonikita112263** [xwikisas/application-task#52]
**ENVIRONMENT**: local XWiki 13.10

**STEP TO REPRODUCE**:

1. Install the latest version of TaskManager (Pro) 
2. Obtain trial license
3. Create a regular user (do not fill first name and last name input fields), and set any image for an avatar to him
4. Go to "TaskManager.WebHome" page
5. Create a task by providing this information as status, and due date, finally assignee this task for the previously created user
7. Save it
8. Go to any dedicated page or sandbox test pages, and add a Task Card macro by providing the id as name of newly created task or use this code `{{taskcard taskid="TaskManager.Wellness360 Initiative" dependencies="false"/}}`
9. Save the page
10. Point the mouse on avatar of user

**ACTUAL RESULT**
You won't see a URL at the bottom of the profile of an assigned user. On the right side, several shadow pictures (triangle and square) are visible only by hovering in the right area. Moreover, in the middle of the square, there's an empty (without text) permalink, which leads to a profile page. 
![image](https://github.com/xwikisas/application-task/assets/56109799/6929dc57-fa8f-428b-9898-8015595a5a17)

**EXPECTED RESULT**
There're no shadow pictures, and hovering over the avatar, the user sees a hyperlink to the user profile page.

**Comment by petrenkonikita112263** [comment]
I've checked several cases, and noticed that my changes aren't good for standard admin account. What isn't cleared - are first name and last name mandatory while creating the new account? If they're, then OMV it's not a bug, but there's a need for improvement.

**Comment by trrenty** [comment]
Indeed. If the user does not have the name and last name set, no link is displayed. It is a bug because the anchor text is set using the first name and the last name without checking if they are filled.

**Comment by trrenty** [comment]
I think the intended behavior is to have the link appear on hover, yes.
