### ISSUE TITLE
Setting the date format in XWiki Preferences for Task Manager has no effect

### ISSUE THREAD

**Issue by petrenkonikita112263** [xwikisas/application-task#56]
**ENVIRONMENT**: local XWiki 13.10

**STEP TO REPRODUCE**:

1. Install the latest version of TaskManager (Pro) 
2. Obtain trial license
3. Create one or several tasks with different created date, due date and completed date 
4. Go to XWiki Prefrences page / Other / Task Manager
5. Scroll down to the end of the page
6. Provide a date mask (like in the example documentation) or use this one "DD-MMM-YYYY" for both fields
7. Save changes (see "Saved" message)

**ACTUAL RESULT**
If you go to the created task or to the main home page where livetable displays created tasks, the displaying format of the date is left untouched. Furthermore trying to create a task the new mask won't be applied. Observe the GIF below 
![msedge_4yUqoG11ad](https://github.com/xwikisas/application-task/assets/56109799/c5378134-036b-4260-97d0-147f33218ff9)

**EXPECTED RESULT**
The mask is applied and the result of this effect is visible.

**Comment by petrenkonikita112263** [comment]
The two input fields which are responsible for date format aren't displayed on "TaskManager.Administration" (which are hidden for regular user)

**Comment by trrenty** [comment]
The date settings in the administration section are not meant to change the way the dates are displayed in the task page, as mentioned in the documentation https://store.xwiki.com/xwiki/bin/view/Extension/TaskApplication#HTaskstorageanddisplaydates. They are used for the date, task and task-report macros. 

However, I can see why one would expect it to behave as you described in this issue.

Maybe we can set this issue to be a possible improvement - for all the dates in the Task Application to follow the configurable date formats. But I'm not sure it would be a great idea.

**Comment by trrenty** [comment]
For now, I'll close the issue with the previous mention.
