### ISSUE TITLE
Add the configuration option to hide tasks

### ISSUE THREAD

**Issue by AndreeaChi** [xwikisas/application-task#64]
Connected to the case from the [task location issue](https://github.com/xwikisas/application-task/issues/63), when importing a space with numerous tasks, the task pages are shown not only in the navigation panel, but also in the breadcrumb trees and in any document tree in general, in the document live tables / data as in the Page Index, in the search results (both quick search and main search page). 

This could become too visually crowded or not very user friendly.

An option to hide them would be useful to have.

**Comment by trrenty** [comment]
The task pages created by the task macros will now be hidden by default.

The view for a user that has `view hidden pages` set to `false`:
Before:
![image](https://github.com/xwikisas/application-task/assets/45433221/6c983515-0c1d-4b0b-93d5-4c3a958e6a91)
After:
![image](https://github.com/xwikisas/application-task/assets/45433221/bd101c4c-daf9-41da-809c-eac6e1311cca)
