### ISSUE TITLE
The top Task card macro displaces the below existing Task macro in page content

### ISSUE THREAD

**Issue by petrenkonikita112263** [xwikisas/application-task#69]
**Prerequisites**:

- XWiki instance 13.10 or 15.x
- Latest version of Task Manager (Pro)
- Trial license
- At least one created task

**Step to reproduce**:

1. Navigate to one of Sandbox pages.
2. Create a new task using Task macro from CKEdiotr toolbar or quick actions command,  leave the reference default as it is, only provide the name and status.
3. Again edit the same page but now add a Task card macro after a newly created task select a task that was created first (or you can use a newly created one), uncheck dependencies (or leave them selected).
4. Again edit the same page and this time add a Task card macro above created task (after paragraph).

**Actual result**:
The Task card macro above Task macro overlaps it and moves out of the border of page to the right side. And below Task card macro don't do that. If you check the source code, it will look like this.

```
Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

{{taskcard taskid="TaskManager.EcoVillage Sustainability Audit" dependencies="false"/}}

{{task createDate="2023/10/05 09:42" reporter="XWiki.Admin" reference="Sandbox.Task_2" status="ToDo"}}
Quest for Clarity
{{/task}}

{{taskcard taskid="TaskManager.CodeQuest Challenge" dependencies="false"/}}
```

Check this GIF (tested on 15.8 but it is also repdocuable in 13.10). Note that it only happens with Task card macro, other macros from Task Manager don't perform such behavior, nor default XWiki macros (info box and etc.)

![msedge_cuKc1ZF1ad](https://github.com/xwikisas/application-task/assets/56109799/ee45606f-3c34-43fb-bc1b-654689c26e32)

**Expected result**:
Task card macro doesn't move the below macro. Each macro is present in a separate line visually.

**Comment by trrenty** [comment]
![image](https://github.com/xwikisas/application-task/assets/45433221/d512fd57-3288-4844-ab0b-7385b3827789)
Fixed
