### ISSUE TITLE
Excessively long task titles

### ISSUE THREAD

**Issue by raphj** [xwikisas/application-task#87]
When creating a task, the title of the task document that is created is excessively long. Some people detail their tasks quite a bit and it might not make sense to use the whole text for the title.

I suggest:

- truncating (with an ellipsis: "…") at some sensible length
- trimming spaces: when the text is indented while writing the task in wiki mode, the indentation is kept in the title, which looks weird

![image](https://github.com/xwikisas/application-task/assets/3817365/2352a3eb-aba5-4474-889f-b5ca5a1d174f)

Another (complementary) idea could be to let the user write a custom title in a parameter, but it does not solve this issue, so this would be for a separate ticket if someone likes the idea. It might add too much UI complexity though.

**Comment by trrenty** [comment]
Truncated the title at 30 characters. As you suggested, I also trimmed the title.

**Comment by michitux** [comment]
> Truncated the title at 30 characters. As you suggested, I also trimmed the title.

This now has the consequence that the full task's name is no longer visible when clicking on the task. As I suggested in #81, maybe it would be possible to store the full content of the task macro in the description of the task?
