### ISSUE TITLE
Missing "InProgress" styling for task dependencies

### ISSUE THREAD

**Issue by petrenkonikita112263** [xwikisas/application-task#89]
It seems that status ToDo has defined 2 different colors 

https://github.com/xwikisas/application-task/blob/3f641e83417fb2641897db6ce8555b83fa6fb93c/application-task-ui/src/main/resources/TaskManager/TaskManagerClass.xml#L882-L887

Logically, the last one will be used in TaskManager.

There's no CSS rule for status InProgress TaskManagerClass file.

**Comment by petrenkonikita112263** [comment]
These color rules used in tasks' dependencies

![image](https://github.com/xwikisas/application-task/assets/56109799/2d59e020-979f-4b9f-a381-ba3454b37c77)

**Comment by trrenty** [comment]
Besides the missing css rule, the used colors were not matching the XWiki theme.

After the update:
![image](https://github.com/xwikisas/application-task/assets/45433221/7ea129de-ca4d-4a45-bab9-9dd89bbb1e03)
