### ISSUE TITLE
Add the option to change the card size of tasks displayed in Kanban board

### ISSUE THREAD

**Issue by AndreeaChi** [xwikisas/application-task#92]
Currently, there is no option to change the card size when using a Kandan board to display tasks based on set statuses.

<img width="824" alt="image" src="https://github.com/xwikisas/application-task/assets/36840106/3006c081-d1bf-4f92-b6b1-9aff118aa982">

**Comment by snazare** [comment]
would be best to be able to define the cards (statuses) to show in the kanban board. **Please investigate why the `columns` parameter is ignored.**

**Comment by KebabRonin** [comment]
This is being resolved on [contrib](https://github.com/xwiki-contrib/macro-kanban/pull/5), after it is merged it is a small update on application-task.
