### ISSUE TITLE
Allow user to set mask type in local format parameter for Date macro instead of global setup from Task Manager Administration page

### ISSUE THREAD

**Issue by petrenkonikita112263** [xwikisas/application-task#97]
Currently, the only way to have the desired result of the following code `{{date value="08/03/2024" format="dd MMM yyyy"/}}` return → **08 Mar 2024**. The User must define the same mask (format) of date in the configuration page: http://localhost/bin/view/TaskManager/Administration.

In some cases, normal users without admin privileges will be interested in calling Date macro by providing 2nd _optional_ parameter _format_ and obtaining a result after saving changes without any further actions in XWiki.

**Comment by trrenty** [comment]
the issue was fixed by #98 . Check the documentation for the date macro. https://store.xwiki.com/xwiki/bin/view/Extension/TaskApplication#documentation
